//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RapidTrackingCloudSingleThread.CloudSourceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudSourceService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGoogleSource", ReplyAction="http://tempuri.org/IService1/GetGoogleSourceResponse")]
        string GetGoogleSource(string seid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGoogleSource", ReplyAction="http://tempuri.org/IService1/GetGoogleSourceResponse")]
        System.Threading.Tasks.Task<string> GetGoogleSourceAsync(string seid, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSource", ReplyAction="http://tempuri.org/IService1/GetSourceResponse")]
        string GetSource(string url, string userAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSource", ReplyAction="http://tempuri.org/IService1/GetSourceResponse")]
        System.Threading.Tasks.Task<string> GetSourceAsync(string url, string userAgent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : RapidTrackingCloudSingleThread.CloudSourceService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<RapidTrackingCloudSingleThread.CloudSourceService.IService1>, RapidTrackingCloudSingleThread.CloudSourceService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGoogleSource(string seid, string keyword) {
            return base.Channel.GetGoogleSource(seid, keyword);
        }
        
        public System.Threading.Tasks.Task<string> GetGoogleSourceAsync(string seid, string keyword) {
            return base.Channel.GetGoogleSourceAsync(seid, keyword);
        }
        
        public string GetSource(string url, string userAgent) {
            return base.Channel.GetSource(url, userAgent);
        }
        
        public System.Threading.Tasks.Task<string> GetSourceAsync(string url, string userAgent) {
            return base.Channel.GetSourceAsync(url, userAgent);
        }
    }
}
